name: Python package

on: [push,  pull_request]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v4
      - name: Setup node
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.x
          cache: yarn
      - name: Lint backend
        run: |
          cd ./onlineshop/source/server/
          yarn install --immutable --immutable-cache --check-cache
          yarn run lint
      - name: Lint frontend
        run: |
          cd ./onlineshop/source/client/
          yarn install --immutable --immutable-cache --check-cache
          yarn run lint
      - name: Test server
        run: |
          cd ./onlineshop/source/server/
          yarn install --immutable --immutable-cache --check-cache
          yarn run test
      - name: Test client
        run: |
          cd ./onlineshop/source/client/
          yarn install --immutable --immutable-cache --check-cache
          yarn run test
